PREFIX qb:      <http://purl.org/linked-data/cube#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX ui:      <http://www.w3.org/ns/ui#>
PREFIX dcat:    <http://www.w3.org/ns/dcat#>
PREFIX foaf:    <http://xmlns.com/foaf/0.1/>
PREFIX pmdcat:  <http://publishmydata.com/pmdcat#> 

SELECT ?record ?count {
    {
        SELECT ?record (COUNT(?mg) AS ?count) 
        WHERE {
            ?record a dcat:CatalogRecord .
            ?record pmdcat:metadataGraph ?mg
        }
        GROUP BY ?record
        HAVING (?count > 1)
    }
    UNION {
        SELECT ?record ?count {
            ?record a dcat:CatalogRecord .
            FILTER NOT EXISTS {
                ?record pmdcat:metadataGraph ?mg
            }
            BIND(0 AS ?count)
        }
    }
}
