PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX foaf:  <http://xmlns.com/foaf/0.1/>
PREFIX pmdcat: <http://publishmydata.com/pmdcat#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# A dataset catalog entry should only be in one Catalog
SELECT ?cat_uri ?ds_uri where {
    ?cat_uri dcat:record/foaf:primaryTopic ?ds_uri .
    ?cat_uri2 dcat:record/foaf:primaryTopic ?ds_uri .

    FILTER(?cat_uri != ?cat_uri2)
}
