PREFIX qb:      <http://purl.org/linked-data/cube#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX ui:      <http://www.w3.org/ns/ui#>

SELECT ?concept {
    ?concept a skos:Concept .
    ?concept skos:broader ?c2 .
    FILTER NOT EXISTS {
        ?c2 a skos:Concept 
    } 
}