PREFIX qb:      <http://purl.org/linked-data/cube#>
PREFIX skos:    <http://www.w3.org/2004/02/skos/core#>
PREFIX ui:      <http://www.w3.org/ns/ui#>

SELECT ?scheme {
    ?scheme a skos:ConceptScheme .
    FILTER NOT EXISTS {
        ?entry <http://publishmydata.com/pmdcat#datasetContents> ?scheme .
    }
    
}