# IC-5. Concept dimensions have code lists

# Every dimension with range skos:Concept must have a qb:codeList.

ASK {
  ?dim a qb:DimensionProperty ;
       rdfs:range skos:Concept .
  FILTER NOT EXISTS { ?dim qb:codeList [] }
}
    