
# IC-6. Only attributes may be optional

# The only components of a qb:DataStructureDefinition that may be marked as optional, using qb:componentRequired are attributes.

ASK {
  ?dsd qb:component ?componentSpec .
  ?componentSpec qb:componentRequired "false"^^xsd:boolean ;
                 qb:componentProperty ?component .
  FILTER NOT EXISTS { ?component a qb:AttributeProperty }
}
    